#!/bin/bash
# =============================================================================
# Lipi Programming Language — Install Script
# GitHub: https://github.com/asaudola-cmyk/LiPi_Lang
# Usage:  curl -sSL https://raw.githubusercontent.com/asaudola-cmyk/LiPi_Lang/main/install.sh | bash
# =============================================================================

set -e

LIPI_VERSION="First 1.0.0 (প্রথম ১.০.০)"
LIPI_REPO="https://github.com/asaudola-cmyk/LiPi_Lang.git"
LIPI_INSTALL_DIR="$HOME/.lipi"
LIPI_BIN_DIR="$HOME/.local/bin"
LIPI_COLOR_GREEN="\033[32m"
LIPI_COLOR_CYAN="\033[36m"
LIPI_COLOR_YELLOW="\033[33m"
LIPI_COLOR_RED="\033[31m"
LIPI_COLOR_BOLD="\033[1m"
LIPI_COLOR_RESET="\033[0m"

header() {
    echo ""
    echo -e "${LIPI_COLOR_BOLD}${LIPI_COLOR_CYAN}"
    echo "  ██╗     ██╗██████╗ ██╗"
    echo "  ██║     ██║██╔══██╗██║"
    echo "  ██║     ██║██████╔╝██║"
    echo "  ██║     ██║██╔═══╝ ██║"
    echo "  ███████╗██║██║     ██║"
    echo "  ╚══════╝╚═╝╚═╝     ╚═╝"
    echo -e "${LIPI_COLOR_RESET}"
    echo -e "  ${LIPI_COLOR_BOLD}Lipi Programming Language${LIPI_COLOR_RESET} — ${LIPI_COLOR_YELLOW}${LIPI_VERSION}${LIPI_COLOR_RESET}"
    echo "  The world's first globally-ready language with Unicode identifiers"
    echo ""
}

ok()   { echo -e "  ${LIPI_COLOR_GREEN}✔${LIPI_COLOR_RESET} $1"; }
fail() { echo -e "  ${LIPI_COLOR_RED}✘ Error: $1${LIPI_COLOR_RESET}"; exit 1; }
info() { echo -e "  ${LIPI_COLOR_CYAN}→${LIPI_COLOR_RESET} $1"; }
warn() { echo -e "  ${LIPI_COLOR_YELLOW}⚠${LIPI_COLOR_RESET} $1"; }

# ─── Check Toolchain ─────────────────────────────────────────────────────────
# WHY: Lipi is 100% Sovereign (Zero Python, Zero Libc, Zero GCC).
# Pre-compiled standalone binaries run directly on bare Linux kernel.
# C compiler (gcc/clang) is only an optional secondary backend.
check_toolchain() {
    info "Checking toolchain (100% Sovereign Native Engine)..."
    CC_CMD=""
    
    # Check optional native C compiler for secondary C codegen backend
    for c_cmd in gcc clang cc; do
        if command -v "$c_cmd" &>/dev/null; then
            CC_CMD="$c_cmd"
            ok "Secondary native C compiler found: $c_cmd"
            break
        fi
    done

    if [ -z "$CC_CMD" ]; then
        info "Standalone direct ELF machine code engine will be used (0% GCC, 0% Libc) 👑"
    fi
}

# ─── Check Git ───────────────────────────────────────────────────────────────
check_git() {
    info "Checking git..."
    if ! command -v git &>/dev/null; then
        fail "git is required but not found.
  
  Install git:
    Ubuntu/Debian:  sudo apt install git
    macOS:          brew install git"
    fi
    ok "git found"
}

# ─── Install ─────────────────────────────────────────────────────────────────
install_lipi() {
    info "Installing to $LIPI_INSTALL_DIR ..."
    
    # Remove old install
    if [ -d "$LIPI_INSTALL_DIR" ]; then
        warn "Existing install found. Updating..."
        git -C "$LIPI_INSTALL_DIR" pull --quiet 2>/dev/null || {
            rm -rf "$LIPI_INSTALL_DIR"
            git clone --quiet --depth=1 "$LIPI_REPO" "$LIPI_INSTALL_DIR"
        }
    else
        git clone --quiet --depth=1 "$LIPI_REPO" "$LIPI_INSTALL_DIR"
    fi
    ok "Lipi repository ready"
}

# ─── Create lipi and lipc commands ──────────────────────────────────────────
create_command() {
    info "Creating 'lipi' and 'lipc' commands..."
    mkdir -p "$LIPI_BIN_DIR"
    
    # 1. Native runner and REPL command
    cp "$LIPI_INSTALL_DIR/bin/lipi" "$LIPI_BIN_DIR/lipi"
    chmod +x "$LIPI_BIN_DIR/lipi"
    ok "Created: $LIPI_BIN_DIR/lipi (Native Runner & REPL)"

    # 2. Verify or bootstrap sovereign compiler binary
    # WHY: Lipi is 100% self-hosted direct machine code. If bin/lipc_bin is not present,
    # boot/bootstrap.sh extracts the pristine binary seed and compiles bin/lipc_bin.
    if [ ! -x "$LIPI_INSTALL_DIR/bin/lipc_bin" ]; then
        info "Bootstrapping sovereign compiler engine via boot/bootstrap.sh..."
        if [ -x "$LIPI_INSTALL_DIR/boot/bootstrap.sh" ]; then
            bash "$LIPI_INSTALL_DIR/boot/bootstrap.sh" || warn "Bootstrap script warning"
        fi
    fi

    # 3. Native compiler command wrapper (lipc)
    cat > "$LIPI_BIN_DIR/lipc" << COMPILER_WRAPPER
#!/bin/bash
# Lipi Programming Language — Native Compiler Wrapper
# Generated by install.sh — Do not edit manually
LIPI_HOME="$LIPI_INSTALL_DIR"
exec "$LIPI_INSTALL_DIR/bin/lipc" "\$@"
COMPILER_WRAPPER
    chmod +x "$LIPI_BIN_DIR/lipc"
    ok "Created: $LIPI_BIN_DIR/lipc (Native Binary Compiler)"

    # 4. Package manager command wrapper (lipipkg)
    cat > "$LIPI_BIN_DIR/lipipkg" << PKG_WRAPPER
#!/bin/bash
# Lipi Programming Language — Package Manager Wrapper
# Generated by install.sh — Do not edit manually
LIPI_HOME="$LIPI_INSTALL_DIR"
exec "$LIPI_INSTALL_DIR/bin/lipipkg" "\$@"
PKG_WRAPPER
    chmod +x "$LIPI_BIN_DIR/lipipkg"
    ok "Created: $LIPI_BIN_DIR/lipipkg (100% Sovereign Package Manager)"

    # 5. Language Server Protocol (lipilsp & lipils alias)
    for lsp_cmd in lipilsp lipils; do
        cat > "$LIPI_BIN_DIR/$lsp_cmd" << LSP_WRAPPER
#!/bin/bash
# Lipi Programming Language — Language Server Protocol Wrapper
# Generated by install.sh — Do not edit manually
LIPI_HOME="$LIPI_INSTALL_DIR"
exec "$LIPI_INSTALL_DIR/bin/lipilsp" "\$@"
LSP_WRAPPER
        chmod +x "$LIPI_BIN_DIR/$lsp_cmd"
        ok "Created: $LIPI_BIN_DIR/$lsp_cmd (Language Server Protocol Engine)"
    done

    # 6. Formatter command wrapper (lipifmt)
    cat > "$LIPI_BIN_DIR/lipifmt" << FMT_WRAPPER
#!/bin/bash
# Lipi Programming Language — Code Formatter Wrapper
# Generated by install.sh — Do not edit manually
LIPI_HOME="$LIPI_INSTALL_DIR"
exec "$LIPI_INSTALL_DIR/bin/lipifmt" "\$@"
FMT_WRAPPER
    chmod +x "$LIPI_BIN_DIR/lipifmt"
    ok "Created: $LIPI_BIN_DIR/lipifmt (Code Formatter Engine)"

    # 7. Debugger command wrapper (lipidbg)
    cat > "$LIPI_BIN_DIR/lipidbg" << DBG_WRAPPER
#!/bin/bash
# Lipi Programming Language — Debugger Engine Wrapper
# Generated by install.sh — Do not edit manually
LIPI_HOME="$LIPI_INSTALL_DIR"
exec "$LIPI_INSTALL_DIR/bin/lipidbg" "\$@"
DBG_WRAPPER
    chmod +x "$LIPI_BIN_DIR/lipidbg"
    ok "Created: $LIPI_BIN_DIR/lipidbg (System Debugger Engine)"

    # 8. Sovereign Database Server wrapper (lipidb_server)
    cat > "$LIPI_BIN_DIR/lipidb_server" << DB_WRAPPER
#!/bin/bash
# Lipi Programming Language — Sovereign Database Server Wrapper
# Generated by install.sh — Do not edit manually
LIPI_HOME="$LIPI_INSTALL_DIR"
exec "$LIPI_INSTALL_DIR/bin/lipidb_server" "\$@"
DB_WRAPPER
    chmod +x "$LIPI_BIN_DIR/lipidb_server"
    ok "Created: $LIPI_BIN_DIR/lipidb_server (Sovereign DB Server)"
}

# ─── Add to PATH ─────────────────────────────────────────────────────────────
setup_path() {
    local added=0
    
    # Detect shell config file
    local shell_configs=("$HOME/.bashrc" "$HOME/.zshrc" "$HOME/.profile" "$HOME/.bash_profile")
    
    for cfg in "${shell_configs[@]}"; do
        if [ -f "$cfg" ]; then
            if ! grep -q 'LIPI_PATH_ADDED' "$cfg" 2>/dev/null; then
                echo "" >> "$cfg"
                echo "# Lipi Programming Language — LIPI_PATH_ADDED" >> "$cfg"
                echo "export PATH=\"\$PATH:$LIPI_BIN_DIR\"" >> "$cfg"
                added=1
            fi
        fi
    done
    
    # Also export for current session
    export PATH="$PATH:$LIPI_BIN_DIR"
    
    if [ "$added" -eq 1 ]; then
        ok "Added $LIPI_BIN_DIR to PATH in shell config"
    else
        ok "$LIPI_BIN_DIR already in PATH config"
    fi
}

# ─── Verify ──────────────────────────────────────────────────────────────────
# WHY: Verify native execution directly without any external runtime.
verify_install() {
    info "Verifying sovereign installation..."
    
    if "$LIPI_BIN_DIR/lipi" --version &>/dev/null; then
        ok "Lipi sovereign toolchain works!"
    elif "$LIPI_BIN_DIR/lipi" -e 'say "install ok"' &>/dev/null; then
        ok "Lipi native runner works!"
    elif [ -x "$LIPI_INSTALL_DIR/bin/lipic" ]; then
        ok "Lipi native compiler ready!"
    else
        warn "Verification check had non-zero status — but binaries are installed in $LIPI_BIN_DIR"
    fi
}

# ─── Print success ───────────────────────────────────────────────────────────
print_success() {
    echo ""
    echo -e "  ${LIPI_COLOR_BOLD}${LIPI_COLOR_GREEN}✔ Lipi installed successfully!${LIPI_COLOR_RESET}"
    echo ""
    echo "  Get started:"
    echo ""
    echo -e "    ${LIPI_COLOR_CYAN}lipi${LIPI_COLOR_RESET}                 → Start interactive REPL"
    echo -e "    ${LIPI_COLOR_CYAN}lipi hello.lp${LIPI_COLOR_RESET}        → Run interpreted (.lp file)"
    echo -e "    ${LIPI_COLOR_CYAN}lipc hello.lp${LIPI_COLOR_RESET}        → Compile to native executable (./hello)"
    echo -e "    ${LIPI_COLOR_CYAN}lipc hello.lp -o app${LIPI_COLOR_RESET} → Compile with custom binary name"
    echo -e "    ${LIPI_COLOR_CYAN}lipi --version${LIPI_COLOR_RESET}       → Show version"
    echo -e "    ${LIPI_COLOR_CYAN}lipi --help${LIPI_COLOR_RESET}          → Show help"
    echo ""
    echo "  Quick test:"
    echo -e "    ${LIPI_COLOR_YELLOW}echo 'say \"Hello, World!\"' | lipi${LIPI_COLOR_RESET}"
    echo ""
    echo "  Documentation:"
    echo "    https://github.com/asaudola-cmyk/LiPi_Lang"
    echo ""
    echo "  ⚠  Restart your terminal (or run: source ~/.bashrc)"
    echo ""
}

# ─── Setup Desktop MIME & Icons ──────────────────────────────────────────────
# WHY: Automatically register *.lp, *.lipi MIME types and install file manager
# icons so Linux desktop file managers (Thunar, Nautilus, Dolphin) render Lipi icons.
setup_desktop_mime() {
    info "Setting up Linux desktop MIME types and file manager icons..."
    if [ -x "$LIPI_INSTALL_DIR/scripts/install_desktop_mime.sh" ]; then
        "$LIPI_INSTALL_DIR/scripts/install_desktop_mime.sh" || warn "Desktop integration encountered a non-fatal warning"
    fi
}

# ─── Uninstall ───────────────────────────────────────────────────────────────
uninstall() {
    echo "Uninstalling Lipi..."
    rm -f "$LIPI_BIN_DIR/lipi"
    rm -f "$LIPI_BIN_DIR/lipc"
    rm -f "$LIPI_BIN_DIR/lipipkg"
    rm -f "$LIPI_BIN_DIR/lipils"
    rm -f "$LIPI_BIN_DIR/lipilsp"
    rm -f "$LIPI_BIN_DIR/lipifmt"
    rm -f "$LIPI_BIN_DIR/lipidbg"
    rm -f "$LIPI_BIN_DIR/lipidb_server"
    rm -rf "$LIPI_INSTALL_DIR"
    echo "Lipi uninstalled."
    exit 0
}

# ─── Main ────────────────────────────────────────────────────────────────────
main() {
    header
    
    if [ "${1:-}" = "--uninstall" ]; then
        uninstall
    fi
    
    check_toolchain
    check_git
    install_lipi
    create_command
    setup_path
    setup_desktop_mime
    verify_install
    print_success
}

main "$@"
